### ISSUE TITLE
Comments after branch not highlighted correctly

### ISSUE THREAD

**Issue by DarkDust** [MKornelsen/vscode-arm64#3]
After a branch, everything up to the line end is treated as the branching target:

```
bl _foo // This comment is highlighted as branching target.
```

This can be fixed by changing the regex for `support.function.bl.arm64` to something to `\\s*(b(?:l|eq|ne|cs|hs|cc|lo|mi|pl|vs|vc|hi|ls|ge|lt|gt|le|al)?)\\s+(\\S+)\\b` (the `.*` is replaced by `\\S+`).

**Comment by MKornelsen** [comment]
Thank you for finding these errors and giving solutions. I have just updated the extension. Let me know if the changes work for you. If you have any other improvements I can make I would be happy to hear those as well.

**Comment by DarkDust** [comment]
Looks fine, thank you very much!
